#!/usr/bin/env python3
"""Build the Adobe API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'Experience Platform': 'Exp. Platform',
    'Marketo Engage': 'Marketo',
    'Experience Manager': 'AEM',
}

LINES = [
    {
        "name": 'Document Cloud',
        "color": '#FA0F00',
        "stations": [
        ('PDF Services', (270, 200)),
        ('PDF Extract', (450, 175)),
        ('Acrobat Sign', (640, 165)),
        ('Stock', (830, 175)),
        ('Commerce', (1000, 200)),
        ],
    },
    {
        "name": 'Experience Cloud',
        "color": '#7B3FE4',
        "stations": [
        ('Analytics', (270, 330)),
        ('Experience Platform', (440, 305)),
        ('Marketo Engage', (620, 305)),
        ('Workfront', (810, 305)),
        ('Experience Manager', (980, 330)),
        ],
    },
    {
        "name": 'Creative & Platform',
        "color": '#5A6275',
        "closed": True,
        "stations": [
        ('Firefly', (820, 470)),
        ('User Mgmt', (910, 555)),
        ('I/O Events', (730, 555)),
        ],
    },
]

URL_OVERRIDES = {
    'PDF Services': 'https://apis.apis.io/apis/adobe/adobe-pdf-services-api/',
    'PDF Extract': 'https://apis.apis.io/apis/adobe/adobe-pdf-extract-api/',
    'Acrobat Sign': 'https://apis.apis.io/apis/adobe/adobe-acrobat-sign-api/',
    'Stock': 'https://apis.apis.io/apis/adobe/adobe-stock-api/',
    'Commerce': 'https://apis.apis.io/apis/adobe/adobe-commerce-api/',
    'Analytics': 'https://apis.apis.io/apis/adobe/adobe-analytics-api/',
    'Experience Platform': 'https://apis.apis.io/apis/adobe/adobe-experience-platform-api/',
    'Marketo Engage': 'https://apis.apis.io/apis/adobe/adobe-marketo-engage-api/',
    'Workfront': 'https://apis.apis.io/apis/adobe/adobe-workfront-api/',
    'Experience Manager': 'https://apis.apis.io/apis/adobe/adobe-experience-manager-api/',
    'Firefly': 'https://apis.apis.io/apis/adobe/adobe-firefly-api/',
    'User Mgmt': 'https://apis.apis.io/apis/adobe/adobe-user-management-api/',
    'I/O Events': 'https://apis.apis.io/apis/adobe/adobe-io-events-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Adobe API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: adobe/openapi · github.com/api-evangelist/adobe',
        out_dir=Path(__file__).resolve().parent,
        out_basename='adobe-subway-map',
        provider_id='adobe',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
